source 'http://rubygems.org'

gem 'rails', '3.1.0'

gem 'sqlite3'

group :assets do
  gem 'sass-rails', '~> 3.1.0'
  gem 'coffee-rails', '~> 3.1.0'
  gem 'uglifier'
end

gem 'jquery-rails'

gem 'tableficate', path: '../../'

group :test do
  gem 'turn', :require => false
  gem 'rspec'
  gem 'capybara'
end
